#!/bin/bash

#run example Redback using stable Moose from Thomas's directory


# submit using "qsub test-stable-redback.pbs"

# Lines starting with "#PBS" are directives to the scheduler

# Job name -- something meaningful to you
#PBS -N test-stable-redback

# Job attributes, used by the scheduler
#PBS -l walltime=00:01:00
#PBS -l vmem=1gb
#PBS -l nodes=1:ppn=2

## Replace this line to run in other queues; if you comment it out you'll get an error.
#PBS -q debug

# Specify output files to go somewhere sensible
##PBS -o ~/test-stable-redback.out
##PBS -e ~/test-stable-redback.err

# Set up mail notifications
##PBS -M email
#PBS -m abe

# The job proper start here
export STABLE_MOOSE_ROOT_DIR=/home/z3506778/stable_MOOSE
echo "starting:" `date`
module load rocks-openmpi
module load opt-python
mpirun -n $PBS_NUM_PPN $STABLE_MOOSE_ROOT_DIR/projects/redback/redback-opt -i $STABLE_MOOSE_ROOT_DIR/projects/redback/tests/benchmark_11_THMC/bench_THMC_CC.i
echo "  ending:" `date`
