#include "RedbackApp.h"
#include "Moose.h"
#include "AppFactory.h"

InputParameters RedbackApp::validParams()
{
  InputParameters params = MooseApp::validParams();
  return params;
}

RedbackApp::RedbackApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  RedbackApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  RedbackApp::associateSyntax(_syntax, _action_factory);
}

RedbackApp::~RedbackApp()
{
}

void
RedbackApp::registerApps()
{
  registerApp(RedbackApp);
}

void
RedbackApp::registerObjects(Factory & factory)
{
}

void
RedbackApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
